<a href="https://colab.research.google.com/github/Naveen-gale/grid-practice/blob/main/gridpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X=df.drop('species',axis=1)
y=df['species']
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42
                                          )

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=18, )

knn.fit(X_train,y_train)
knn.score(X_test,y_test)

1.0

In [ ]:
from sklearn.model_selection import GridSearchCV

clasif = GridSearchCV(
    knn,
    {
        'n_neighbors': [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    },
    cv=5,
    return_train_score=False
)

In [ ]:
clasif.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=18),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20]})

In [ ]:
clasif.score(X, y)

0.9733333333333334

In [ ]:
result = pd.DataFrame(clasif.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008352,0.002644,0.010363,0.004934,1,{'n_neighbors': 1},0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,18
1,0.004235,0.000924,0.005180,0.000182,2,{'n_neighbors': 2},0.966667,0.933333,0.933333,0.900000,1.0,0.946667,0.033993,20
2,0.003673,0.000285,0.004945,0.000418,3,{'n_neighbors': 3},0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,10
3,0.004789,0.002647,0.007708,0.005001,4,{'n_neighbors': 4},0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,6
4,0.003417,0.000187,0.004688,0.000071,5,{'n_neighbors': 5},0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
5,0.003315,0.000096,0.004658,0.000120,6,{'n_neighbors': 6},0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
6,0.003375,0.000121,0.005902,0.001881,7,{'n_neighbors': 7},0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
7,0.004251,0.001936,0.006083,0.002791,8,{'n_neighbors': 8},0.966667,1.000000,0.933333,0.933333,1.0,0.966667,0.029814,10
8,0.004963,0.001633,0.006253,0.001019,9,{'n_neighbors': 9},0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
9,0.004307,0.000320,0.005844,0.000440,10,{'n_neighbors': 10},0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,1
10,0.003897,0.000119,0.005352,0.000162,11,{'n_neighbors': 11},0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,1
11,0.003865,0.000349,0.005232,0.000374,12,{'n_neighbors': 12},0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,1
12,0.003686,0.000079,0.005000,0.000103,13,{'n_neighbors': 13},0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,6
13,0.003970,0.000983,0.005039,0.000309,14,{'n_neighbors': 14},0.933333,1.000000,0.966667,0.933333,1.0,0.966667,0.029814,16
14,0.003594,0.000147,0.005053,0.000058,15,{'n_neighbors': 15},0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,10
15,0.003406,0.000075,0.005306,0.001100,16,{'n_neighbors': 16},0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,10
16,0.003313,0.000076,0.004789,0.000086,17,{'n_neighbors': 17},0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,10
17,0.006832,0.001768,0.010018,0.000973,18,{'n_neighbors': 18},0.933333,1.000000,0.966667,0.933333,1.0,0.966667,0.029814,16
18,0.004394,0.001808,0.006215,0.002612,19,{'n_neighbors': 19},0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,10
19,0.003336,0.000039,0.004709,0.000168,20,{'n_neighbors': 20},0.933333,1.000000,0.933333,0.933333,1.0,0.960000,0.032660,18