<a href="https://colab.research.google.com/github/Naveen-gale/ml-part-4/blob/main/intership_scam_ml_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
files = files.upload()

Saving internship_scam_dataset.csv to internship_scam_dataset.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("internship_scam_dataset.csv")

In [4]:
df.head()

,message_text,sender_domain,email_domain_type,company_name,asks_money,fee_amount,registration_fee,training_fee,certificate_fee,security_deposit,...,urgency_words,grammar_score,offer_letter_provided,contact_number_exists,stipend_amount,work_mode,internship_duration,selection_without_interview,guaranteed_job_offer,label
0,"Hello, Your application for Content Writing In...",zenithcorp.com,official,Zenith Corp,0,0,0,0,0,0,...,0,93.1,0,1,20000,Remote,3,0,0,0
1,Congratulations! We reviewed your profile and ...,mail.com,free,Alpha Labs,1,4536,4536,0,0,0,...,3,74.4,0,1,15000,Onsite,1,1,1,1
2,URGENT: You have been selected for Business De...,mail.com,free,Acme Systems,1,676,0,676,0,0,...,4,44.1,0,1,15000,Remote,1,1,1,1
3,You are hired! Nova Corp is offering an intern...,hotmail.com,free,Nova Corp,1,3032,0,0,3032,0,...,1,36.8,1,1,80000,Onsite,4,1,1,1
4,Congratulations! We reviewed your profile and ...,mail.com,free,Synergy Solutions,1,6458,0,0,0,6458,...,4,59.2,1,0,0,Remote,5,0,0,1

In [5]:
df.isnull().sum()

message_text                   0
sender_domain                  0
email_domain_type              0
company_name                   0
asks_money                     0
fee_amount                     0
registration_fee               0
training_fee                   0
certificate_fee                0
security_deposit               0
website_exists                 0
company_age                    0
linkedin_exists                0
linkedin_followers             0
linkedin_employees             0
urgency_words                  0
grammar_score                  0
offer_letter_provided          0
contact_number_exists          0
stipend_amount                 0
work_mode                      0
internship_duration            0
selection_without_interview    0
guaranteed_job_offer           0
label                          0
dtype: int64

In [8]:
X= df.drop('label', axis=1)

In [9]:
y= df['label']

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

text_features = tfidf.fit_transform(df["message_text"])

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["work_mode"] = le.fit_transform(df["work_mode"])

In [16]:
pd.get_dummies(data= df)

,asks_money,fee_amount,registration_fee,training_fee,certificate_fee,security_deposit,website_exists,company_age,linkedin_exists,linkedin_followers,...,company_name_Zenith Group,company_name_Zenith Inc,company_name_Zenith Innovations,company_name_Zenith LLC,company_name_Zenith Labs,company_name_Zenith Networks,company_name_Zenith Solutions,company_name_Zenith Studios,company_name_Zenith Systems,company_name_Zenith Tech
0,0,0,0,0,0,0,1,15,1,577733,...,False,False,False,False,False,False,False,False,False,False
1,1,4536,4536,0,0,0,0,1,0,0,...,False,False,False,False,False,False,False,False,False,False
2,1,676,0,676,0,0,0,0,1,329,...,False,False,False,False,False,False,False,False,False,False
3,1,3032,0,0,3032,0,0,2,0,0,...,False,False,False,False,False,False,False,False,False,False
4,1,6458,0,0,0,6458,1,3,1,384,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,1,15,0,0,...,False,False,False,False,False,False,False,False,False,False
9996,0,0,0,0,0,0,1,65,1,837216,...,False,False,False,False,False,False,False,False,False,False
9997,0,0,0,0,0,0,1,36,1,148881,...,False,False,False,False,False,False,False,False,False,False
9998,1,6758,6758,0,0,0,1,3,1,25,...,False,False,False,False,False,False,False,False,False,False
9999,0,0,0,0,0,0,1,98,1,588262,...,False,False,False,False,False,False,False,False,False,False

In [17]:
corr = df.corr(numeric_only=True)['label'].sort_values(ascending=False)

print(corr.head(20))

label                          1.000000
asks_money                     0.838449
selection_without_interview    0.826399
fee_amount                     0.708098
urgency_words                  0.704134
guaranteed_job_offer           0.699859
stipend_amount                 0.497216
offer_letter_provided          0.392200
security_deposit               0.303080
certificate_fee                0.301518
registration_fee               0.301508
training_fee                   0.300285
work_mode                      0.143152
internship_duration           -0.155750
contact_number_exists         -0.219533
linkedin_exists               -0.603033
website_exists                -0.660348
linkedin_employees            -0.709344
linkedin_followers            -0.716112
company_age                   -0.757514
Name: label, dtype: float64

In [18]:
drop_cols = [col for col in df.columns if "company_name_" in col]

df = df.drop(columns=drop_cols)

In [22]:
X = df.drop(["label", "message_text"], axis=1)
y = df["label"]

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [26]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

ValueError: could not convert string to float: 'nexlabs.com'

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000)

text_features = tfidf.fit_transform(df["message_text"])

In [27]:
X = df.drop([
    "label",
    "message_text",
    "sender_domain",
    "email_domain_type",
    "company_name"
], axis=1)

y = df["label"]

In [28]:
print(X.dtypes.unique())

[dtype('int64') dtype('float64')]

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [30]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [31]:
print(X.select_dtypes(include=['object']).columns)

Index([], dtype='object')

In [33]:
y_pred = rf.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracep = accuracy_score(y_test, y_pred)

In [37]:
print(accuracep)

1.0